ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.1
- SUB = 0.1
- MUL = 0.1
- MATMUL = 0.1
- RELU = 0.1
- SIGMOID = 0.1

Instances:
- ADD = 50
- SUB = 16
- MUL = 32
- MATMUL = 34
- RELU = 17
- SIGMOID = 16

InjectMode: "errorRate"
