ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.5
- SUB = 0.5
- MUL = 0.5
- MATMUL = 0.5
- RELU = 0.5
- SIGMOID = 0.5
- CONV2D = 0.5
- MAX-POOL = 0.5

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
