ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.1
- SUB = 0.1
- MUL = 0.1
- MATMUL = 0.1
- RELU = 0.1
- SIGMOID = 0.1
- CONV2D = 0.1
- MAX-POOL = 0.1

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
