ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.2
- SUB = 0.2
- MUL = 0.2
- MATMUL = 0.2
- RELU = 0.2
- SIGMOID = 0.2
- CONV2D = 0.2
- MAX-POOL = 0.2

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
