ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.4
- SUB = 0.4
- MUL = 0.4
- MATMUL = 0.4
- RELU = 0.4
- SIGMOID = 0.4
- CONV2D = 0.4
- MAX-POOL = 0.4

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
