ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.5
- SUB = 0.5
- MUL = 0.5
- MATMUL = 0.5
- RELU = 0.5
- SIGMOID = 0.5

Instances:
- ADD = 50
- SUB = 16
- MUL = 32
- MATMUL = 34
- RELU = 17
- SIGMOID = 16

InjectMode: "errorRate"
