ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.4
- SUB = 0.4
- MUL = 0.4
- MATMUL = 0.4
- RELU = 0.4
- SIGMOID = 0.4

Instances:
- ADD = 50
- SUB = 16
- MUL = 32
- MATMUL = 34
- RELU = 17
- SIGMOID = 16

InjectMode: "errorRate"
