ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 1.0
- SUB = 1.0
- MUL = 1.0
- MATMUL = 1.0
- RELU = 1.0
- CONV2D = 1.0
- MAX-POOL = 1.0

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "dynamicInstance"
