ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.2
- SUB = 0.2
- MUL = 0.2
- MATMUL = 0.2
- RELU = 0.2
- CONV2D = 0.2
- MAX-POOL = 0.2

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
