ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.1
- SUB = 0.1
- MUL = 0.1
- MATMUL = 0.1
- RELU = 0.1
- CONV2D = 0.1
- MAX-POOL = 0.1

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
