ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.6
- SUB = 0.6
- MUL = 0.6
- MATMUL = 0.6
- RELU = 0.6
- CONV2D = 0.6
- MAX-POOL = 0.6

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
