ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.3
- SUB = 0.3
- MUL = 0.3
- MATMUL = 0.3
- RELU = 0.3
- CONV2D = 0.3
- MAX-POOL = 0.3

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
