ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.5
- SUB = 0.5
- MUL = 0.5
- MATMUL = 0.5
- RELU = 0.5
- CONV2D = 0.5
- MAX-POOL = 0.5

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
