ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.4
- SUB = 0.4
- MUL = 0.4
- MATMUL = 0.4
- RELU = 0.4
- CONV2D = 0.4
- MAX-POOL = 0.4

Instances:
- ADD = 4
- SUB = 1
- MUL = 2
- MATMUL = 2
- RELU = 3
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
