ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.3
- SUB = 0.3
- MUL = 0.3
- MATMUL = 0.3
- RELU = 0.3
- SIGMOID = 0.3
- CONV2D = 0.3
- MAX-POOL = 0.3

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
