ScalarFaultType: Rand-element
TensorFaultType: Rand-element

Ops:
- ADD = 0.6
- SUB = 0.6
- MUL = 0.6
- MATMUL = 0.6
- RELU = 0.6
- SIGMOID = 0.6
- CONV2D = 0.6
- MAX-POOL = 0.6

Instances:
- ADD = 34
- SUB = 12
- MUL = 24
- MATMUL = 1
- RELU = 9
- SIGMOID = 8
- CONV2D = 17
- MAX-POOL = 3

InjectMode: "errorRate"
