ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.4
- MATMUL = 0.4
- RELU = 0.4
- CONV2D = 0.4
- MAX-POOL = 0.4

Instances:
- ADD = 5
- MATMUL = 3
- RELU = 4
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
