ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.2
- MATMUL = 0.2
- RELU = 0.2
- CONV2D = 0.2
- MAX-POOL = 0.2

Instances:
- ADD = 5
- MATMUL = 3
- RELU = 4
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
