ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.5
- MATMUL = 0.5
- RELU = 0.5
- CONV2D = 0.5
- MAX-POOL = 0.5

Instances:
- ADD = 5
- MATMUL = 3
- RELU = 4
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
