ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element

Ops:
- ADD = 0.3
- MATMUL = 0.3
- RELU = 0.3
- CONV2D = 0.3
- MAX-POOL = 0.3

Instances:
- ADD = 5
- MATMUL = 3
- RELU = 4
- CONV2D = 2
- MAX-POOL = 2

InjectMode: "errorRate"
